# Site settings
name: 小雨点
email: 15517526173@163.com
author: 
url: 
resume_site: # http://www.hifreud.com/Resume.io/
github: # https://github.com/luoyan35714/
baseurl: "/eraincode"
description: 勇士都是孤独的,你能忍受吗？
meta_description: 小雨点;来自上天，归落凡尘
motto: It's our wits that make us men.
banner: 勇士都是孤独的,你能忍受吗？

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: luoyan35714

# Build settings
markdown: kramdown

baidu_analysis: # 94be4b0f9fc5d94cc0d0415ea6761ae9
future: true
